import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/global-components/Nav";
import Navbar from "@/global-components/navbarHome";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-20">
          <Nav />
        </div>
        {children}
      </body>
    </html>
  );
}
