import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/global-components/Nav";
import FooterAlt from "@/global-components/FooterAlt";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-20 px-14 bg-white shadow-lg">
          <Nav />
        </div>
        <div className="bg-gradient-to-r from-gray-100 via-[#bce1ff] to-gray-100">
          {children}
        </div>
        <div className="px-20 bg-white pt-6 pb-2" style={{ boxShadow: "1px 1px 1px 1px grey" }}>
          <FooterAlt />
        </div>
      </body>
    </html>
  );
}
