import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/global-components/Nav";
import Footer from "@/global-components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-20">
          <Nav />
        </div>
        <div className="bg-gradient-to-r from-gray-100 via-[#bce1ff] to-gray-100">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
